swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:  
  /predict-light:
    get:
      operationId: "predict.cluster"
      tags:
        - Get cluster label of light
      summary: "Get cluster label of light"
      description: "Get cluster label of light"
      parameters:
        - name: light
          in: query
          description: Light
          required: true
          type: number        
        
      responses:
        200:
          description: "Successful prediction"          
  
  /predict-hydration-time:
    get:  
      operationId: "predict.hydrationTime"
      tags:
        - Predict time until next hydration
      summary: "Predict time until next hydration"
      description: "Predicts the time until the next hydration based on temperature, humidity, and other factors."
      parameters:
        - name: hour
          in: query
          description: Hour of the day
          type: integer
        - name: day_of_week
          in: query
          description: Day of the week 
          type: integer
        - name: temperature
          in: query
          description: Temperature in Celsius
          type: number
        - name: humidity
          in: query
          description: Humidity percentage
          type: number
      responses:
        200:
          description: "Successful prediction of hydration time"